#! /bin/sh

bspc config border_width        2
bspc config window_gap         16

bspc config normal_border_color "#2b3032"
bspc config focused_border_color "#2b3032"
bspc config active_border_color "#2b3032"
bspc config presel_border_color "#DFDFDF"
bspc config focused_locked_border_color "#2b3032"
bspc config active_locked_border_color "#2b3032"
bspc config normal_locked_border_color "#2b3032"
bspc config focused_sticky_border_color "#2b3032"
bspc config active_sticky_border_color "#2b3032"
bspc config normal_sticky_border_color "#2b3032"
bspc config focused_private_border_color "#2b3032"
bspc config active_private_border_color "#2b3032"
bspc config normal_private_border_color "#2b3032"
bspc config urgent_border_color "#2b3032"

bspc config split_ratio         0.62
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DVI-I-0 -d 6 7 8 9 0

bspc rule -a conky manage=off
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam follow=no floating=on
bspc rule -a streaming_client desktop=5
bspc rule -a Discord desktop=7
bspc rule -a wrapper-1.0 border=off center=off
bspc rule -a "PVP.net Client" border=off

bspc config top_padding 6
bspc config bottom_padding 26

bspc config external_rules_command "/home/thilo/dotfiles/config/bspwm/external_rules.sh"

# Autostart
xrandr --output HDMI-0 --primary --auto --output DVI-I-0 --auto --right-of HDMI-0 &
feh --bg-tile "/home/thilo/.wallpaper.jpg" &
xset s off -dpms &
xsetroot -cursor_name left_ptr &
xinput set-prop 9 135 1.600000, 0.000000, 0.000000, 0.000000, 1.600000, 0.000000, 0.000000, 0.000000, 1.000000 &
compton -cCGf --backend glx --paint-on-overlay --vsync opengl-swc &
bspc desktop -f 1 &
bspc control --subscribe| while read; do bash ~/dotfiles/config/bspwm/titlebars.sh ; done &
~/dotfiles/config/bspwm/adjust_gaps.sh &
~/dotfiles/config/bspwm/taskbar.sh &
nm-applet & sleep 0.2 && pa-applet & sleep 0.2 && pactray &
redshift &
unclutter &
nemo -n &
dropbox start &
discord &
linconnect-server &
echo "/home/thilo" > /tmp/wmdirectory &
sleep 3 && stalonetray -t --grow-gravity E --geometry 1x1+1832-0 --icon-gravity E -s 26 -i 16 --scrollbars horizontal --max-geometry 3x1 &
xfce4-panel -d & sleep 5 && xdotool windowunmap $(xdotool search xfce4-panel|tail -1) &
sleep 5 && caffeine -a &
