#! /bin/sh

bspc config border_width        0
bspc config window_gap         16

bspc config normal_border_color "#1d1f21"
bspc config focused_border_color "#1d1f21"
bspc config active_border_color "#1d1f21"
bspc config presel_feedback_color "#1d1f21"
bspc config focused_locked_border_color "#1d1f21"
bspc config active_locked_border_color "#1d1f21"
bspc config normal_locked_border_color "#1d1f21"
bspc config focused_sticky_border_color "#1d1f21"
bspc config active_sticky_border_color "#1d1f21"
bspc config normal_sticky_border_color "#1d1f21"
bspc config focused_private_border_color "#1d1f21"
bspc config active_private_border_color "#1d1f21"
bspc config normal_private_border_color "#1d1f21"
bspc config urgent_border_color "#1d1f21"

bspc config split_ratio         0.62
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config click_to_focus      true

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor HDMI-0 -d 6 7 8 9 0

bspc rule -a streaming_client desktop=5
bspc rule -a Discord desktop=7
bspc rule -a Wrapper-1.0 border=off center=off
bspc rule -a "PVP.net Client" border=off
bspc rule -a Pamac-updater state=floating

bspc config top_padding 6
bspc config bottom_padding 26

# Autostart
# xrandr --output HDMI-0 --primary --auto --output DVI-I-0 --auto --right-of HDMI-0 &
sxhkd &
feh --bg-fill '/home/thilo/Downloads/naja.jpe' &
xset s off &
xset dpms 36000 36000 36000 &
xsetroot -xcf /usr/share/icons/Adwaita/cursors/left_ptr 24 &
xinput set-prop 9 135 1.600000, 0.000000, 0.000000, 0.000000, 1.600000, 0.000000, 0.000000, 0.000000, 1.000000 &
compton --backend glx --unredir-if-possible &
bspc desktop -f 1 &
~/dotfiles/config/bspwm/titlebars.sh &
~/dotfiles/config/bspwm/adjust_gaps.sh &
#~/dotfiles/config/bspwm/taskbar.sh &
echo "/home/thilo" > /tmp/wmdirectory &
tint2 & tint2 -c ~/.config/tint2/tint2rc2 &
nm-applet & sleep 0.2 && pa-applet & sleep 0.2 && sudo -E pamac-tray &
redshift &
unclutter &
nautilus --no-default-window &
dropbox start &
discord &
linconnect-server &
#sleep 3 && stalonetray -t --grow-gravity E --geometry 1x1+2472-3 --icon-gravity E -s 26 -i 16 --scrollbars horizontal --max-geometry 10x1 --kludges force_icons_size &
xfce4-panel -d & sleep 5 && xdotool windowunmap $(xdotool search xfce4-panel|tail -1) &
sleep 3 && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n tint2) &
